version: '3'

services:
  user-service:
    build: .
    container_name: user-service
    hostname: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://db:27017/user
      - KAFKA_BROKER=${KAFKA_BROKER}
      # - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
    networks:
      - tasty-net
networks:
  tasty-net:
    external: true