version: '3'

services:
  user-services:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://db:27017/user
      - KAFKA_BROKER=${KAFKA_BROKER}
      # - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
    networks:
      - tasty-net
  db:
    image: mongo:8.0.0-rc13-jammy
    ports:
      - "27017:27017"
    volumes:
      - 'db_data:/data/db'
    networks:
      - tasty-net
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    networks:
      - tasty-net
  kafka:
    image: bitnami/kafka:3.4.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - tasty-net
volumes:
  db_data:
    driver: local

networks:
  tasty-net:
    external: true